services:
  store_service:
    build: .
    container_name: store_service
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      db_store_service:
        condition: service_healthy
    networks:
      - app-network    

  db_store_service:
    image: postgres:alpine
    container_name: db_store_service
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
    networks:
      - app-network          

volumes:
  db:

networks:
  app-network:
    external: true