name: Build and Publish Docker

on:
  push:
    branches:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: manuelhernandezcarrasco
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract version
        id: extract_version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/v} | sed 's/\//-/g')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}